# Lekce 02 - Základní datové typy I

Obsah:

* jak si pomoct: `help()` a doplňování klávesou Tab
* čtení chybových hlášení
* proměnné a pojmenování
* čísla `int` a `float`, operátory
* přesnost desetinných čísel
* konverze typů
* `bool` a porovnání
* `None`
* řetězce: indexování, slicing, metody
* f-stringy a formátování čísel
* `input()` a `print()`

Větvení (`if`) a cykly (`for`, `while`) přijdou v lekcích 4 a 5. V této lekci je
nepotřebujeme.

## 1. Jak si pomoct

* `help(jmeno)` vypíše dokumentaci k funkci, typu nebo modulu
* začátek jména a klávesa `Tab` nabídne doplnění
* `hodnota.` a klávesa `Tab` nabídne, co všechno s hodnotou umíme dělat
* `dir(hodnota)` vypíše totéž jako seznam

Nápovědu používejte průběžně, není to známka neznalosti. Programátoři v ní listují
pořád.

In [ ]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.

    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



Doplňování si vyzkoušejte sami. Napište do nové buňky `kod.` a stiskněte `Tab`:

```python
kod = "SO-01"
kod.        # + Tab -> nabidka vsech metod retezce
kod.upper(  # + Shift+Tab -> napoveda k metode
```

## 2. Čtení chybových hlášení

Chyba není katastrofa, je to informace. Hlášení (traceback) se čte **odspodu**:

* **poslední řádek** je nejdůležitější: *typ chyby* a *zpráva*
* nad ním je označený řádek kódu, na kterém se to stalo
* šipka `^` ukazuje na místo v řádku

Následující buňky jsou **úmyslně chybné**. Spusťte je a přečtěte si hlášení.

In [1]:
# SyntaxError: Python zapisu nerozumi, kod se vubec nespustil
plocha = 12.5 * * 8.0

SyntaxError: invalid syntax (863904537.py, line 2)

In [2]:
# NameError: pouzite jmeno neexistuje - typicky preklep
objem = 25.0
print(objme)

NameError: name 'objme' is not defined

In [4]:
# TypeError: operace nema smysl pro dane typy
pocet_prvku = "12"
print(pocet_prvku * 2.5)

TypeError: can't multiply sequence by non-int of type 'float'

In [5]:
# ValueError: typ je spravny, ale konkretni hodnota se pouzit neda
tloustka = float("0,25")

ValueError: could not convert string to float: '0,25'

### Nejčastější chyby

| Typ chyby | Co znamená | Typická příčina |
|---|---|---|
| `SyntaxError` | Python zápisu nerozumí | chybějící závorka, dvojtečka, přebytečný operátor |
| `IndentationError` | špatné odsazení | zapomenuté nebo nestejné odsazení bloku |
| `NameError` | jméno neexistuje | překlep, nespuštěná buňka výše |
| `TypeError` | operace nejde pro tyto typy | sčítání textu a čísla |
| `ValueError` | typ je správný, hodnota ne | `float("0,25")`, `int("abc")` |
| `ZeroDivisionError` | dělení nulou | nulový jmenovatel |

Postup, když něco spadne: přečíst poslední řádek, najít označený řádek kódu,
vypsat si `type()` a hodnoty proměnných, které do něj vstupují.

## 3. Proměnné a pojmenování

Proměnná je jméno, pod kterým je uložená hodnota. Vznikne přiřazením `=`.

In [6]:
delka_desky = 12.5      # snake_case, slova oddelena podtrzitkem
pocet_prvku = 120
print(delka_desky, pocet_prvku)

12.5 120


Pravidla a zvyky:

* jméno začíná písmenem nebo `_`, dál mohou být i číslice
* bez mezer a **bez diakritiky** - `tloustka`, ne `tlouštka`
* rozlišují se malá a velká písmena: `Objem` a `objem` jsou dvě různá jména
* jméno má říkat, co v proměnné je: `objem_betonu` místo `x`
* nepoužívejte `l`, `I`, `O` samostatně, jsou k nerozeznání od číslic
* konstanty se zvykem píšou velkými písmeny: `DPH = 0.21`
* klíčová slova jazyka použít nelze

In [7]:
import keyword

print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


## 4. Typ hodnoty

Typ nese **hodnota**, ne proměnná. Proměnná je jen jméno, které na hodnotu
ukazuje - proto se do stejného jména dá uložit nejdřív číslo a pak text
(dynamické typování). Typ zjistíme funkcí `type()`.

In [8]:
print(type(25))
print(type(12.5))
print(type("C25/30"))
print(type(True))
print(type(None))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
<class 'NoneType'>


## 5. Čísla: `int` a `float`

* `int` je celé číslo: `25`, `-3`, `120`, lze zapsat s podtržítky `1_000_000`
* `float` je desetinné číslo: `12.5`, `0.25`. Desetinná část se píše **tečkou**
* Python zvládá i komplexní čísla (`1+2j`), v kurzu je nepotřebujeme

| Operátor | Význam | Příklad |
|---|---|---|
| `+` `-` `*` | součet, rozdíl, součin | `2 * 3` |
| `/` | dělení, výsledek je vždy `float` | `7 / 2` -> `3.5` |
| `//` | celočíselné dělení | `7 // 2` -> `3` |
| `%` | zbytek po dělení | `7 % 2` -> `1` |
| `**` | mocnina | `2 ** 3` -> `8` |

In [9]:
delka = 12.5
sirka = 8.0
tloustka = 0.25

objem = delka * sirka * tloustka
print(objem)

25.0


In [10]:
print(7 / 2)      # deleni vraci vzdy float
print(7 // 2)     # celociselne deleni
print(7 % 2)      # zbytek po deleni
print(2 ** 3)     # mocnina
print(2 + 3 * 4)  # priorita jako v matematice
print((2 + 3) * 4)

3.5
3
1
8
14
20


Celočíselné dělení se hodí i na praktické otázky. Kolik plných autodomíchávačů
o kapacitě 8 m3 odveze 25 m3 betonu a co zbyde?

In [11]:
objem = 25.0
kapacita = 8.0

print(objem // kapacita)   # pocet plnych jizd
print(objem % kapacita)    # zbytek na posledni jizdu

3.0
1.0


## 6. Přesnost desetinných čísel

`float` je v počítači uložený ve dvojkové soustavě a většina desetinných čísel
se do ní nevejde přesně - podobně jako 1/3 nejde přesně zapsat desetinně.
Výsledek proto bývá o nepatrný zlomek jiný, než čekáme.

In [ ]:
print(0.1 + 0.2)
print(0.1 + 0.2 == 0.3)
# nebo take
print(1.0e16 - 1.0e16 + 1.0 == 1.0e16 + 1.0 - 1.0e16)

0.30000000000000004
False
False


Důsledek pro praxi:

* **desetinná čísla nikdy neporovnávejte na rovnost** pomocí `==`
* pro porovnání použijte `math.isclose()` (`math` je balík, `isclose()` je funkce v tomto balíku)
* pro výpis použijte zaokrouhlení `round(hodnota, 2)` nebo f-string `:.2f`
* `round()` zaokrouhluje, `int()` desetinnou část odřízne

In [13]:
import math

vymera = 0.1 + 0.2

print(round(vymera, 2))
print(math.isclose(vymera, 0.3))

0.3
True


## 7. Konverze typů

Hodnotu lze převést na jiný typ zabudovanými funkcemi `int()`, `float()`, `str()`.

In [14]:
print(int("42"), type(int("42")))
print(float("12.5"))
print(str(25.0), type(str(25.0)))
print(int(3.9))     # desetinna cast se odrizne, nezaokrouhluje se
print(round(3.9))   # takhle se zaokrouhluje

42 <class 'int'>
12.5
25.0 <class 'str'>
3
4


Konverze ale musí dávat smysl, jinak skončí `ValueError`:

In [15]:
print(int("C25/30"))

ValueError: invalid literal for int() with base 10: 'C25/30'

## 8. `bool` a porovnání

Typ `bool` má jen dvě hodnoty: `True` a `False`. Vzniká typicky porovnáním nebo je návratovou hodnotou funkce či metody, viz. `math.isclose()`

| Operátor | Význam |
|---|---|
| `==` | rovná se |
| `!=` | nerovná se |
| `<` `>` `<=` `>=` | menší, větší, menší nebo rovno, větší nebo rovno |

Pozor na rozdíl: `=` přiřazuje hodnotu do proměnné, `==` dvě hodnoty porovnává.

In [ ]:
pruhyb = 18.5      # mm
limit = 24.0       # mm

print(pruhyb < limit)
print(pruhyb == limit)
print(type(pruhyb < limit))

True
False
<class 'bool'>


Podmínky se kombinují operátory `and`, `or`, `not`:

In [17]:
beton_ok = True
kryti_ok = False

print(beton_ok and kryti_ok)   # plati oboji
print(beton_ok or kryti_ok)    # plati alespon jedno
print(not beton_ok)            # obraceni

False
True
False


In [ ]:
# True se v poctech chova jako 1, False jako 0
print(True + True) # Citelnost? Radeji nepouzivat
print(int(False))

2
0


V této lekci jen zapisujeme **hodnoty** porovnání. Rozhodování podle podmínky
(`if`) je obsahem lekce 4.

## 9. `None`

`None` je hodnota, která znamená *nic*, *nevyplněno*. Používá se pro chybějící
údaj - třeba atribut prvku, který v modelu není zadaný. Vrací ji i funkce, která
nic nevrací.

In [ ]:
trida_prostredi = None
print(trida_prostredi, type(trida_prostredi))

vysledek = print("tohle print vypise")
print(vysledek)     # funkce print() nic nevraci, tedy vrací hodnotu None

None <class 'NoneType'>
tohle print vypise
None


## 10. Řetězce (`str`)

Řetězec je text v uvozovkách - jednoduchých nebo dvojitých, na obou koncích
stejných. Znaky mají index, který začíná **nulou**, záporný index se počítá
od konce.

In [20]:
kod = "SO-01_2NP_C25-30"

print(len(kod))
print(kod[0], kod[1], kod[-1])
print(kod[0:5])   # slicing: od indexu 0 do 5, pet znaku bez pateho
print(kod[6:9])
print(kod[10:])   # od indexu 10 do konce

16
S O 0
SO-01
2NP
C25-30


Řetězec je **neměnný** (immutable) - jednotlivý znak přepsat nelze:

In [21]:
kod = "SO-01"
kod[0] = "X"

TypeError: 'str' object does not support item assignment

Místo toho se vyrobí nový řetězec:

In [22]:
kod = "SO-01"
novy = "X" + kod[1:]
print(novy)

XO-01


### Užitečné metody

Metoda je funkce, která patří k hodnotě a volá se tečkou za ní. Žádná z nich
původní řetězec nemění, všechny vracejí nový.

In [23]:
hodnota = "  c25/30  "

print(hodnota.strip())            # odstrani mezery na krajich
print(hodnota.strip().upper())    # metody lze radit za sebe
print(hodnota.strip().replace("/", "-"))
print("C25/30".startswith("C"))
print("2NP" in "SO-01_2NP_C25-30")   # obsahuje retezec dany usek?

c25/30
C25/30
c25-30
True
True


In [24]:
# split() rozdeli retezec podle oddelovace; vysledkem je seznam,
# kterym se budeme zabyvat v lekci 3
print("SO-01_2NP_C25-30".split("_"))

['SO-01', '2NP', 'C25-30']


Speciální znaky se zapisují zpětným lomítkem:

In [ ]:
print("prvni radek\ndruhy radek")   # \n je novy radek
print("sloupec\tsloupec")           # \t je tabulator
print("uvozovky uvnitr: \"C25/30\"") # escaped quotes
# lze take
print('uvozovky uvnitr: "C25/30"')

prvni radek
druhy radek
sloupec	sloupec
uvozovky uvnitr: "C25/30"
uvozovky uvnitr: "C25/30"


## 11. f-stringy a formátování čísel

Do textu se dají vložit hodnoty proměnných: před uvozovky se napíše `f` a hodnota
se vloží ve složených závorkách. Za dvojtečkou se dá určit, jak se má vypsat.

| Zápis | Význam |
|---|---|
| `{x:.2f}` | dvě desetinná místa |
| `{x:>10}` | zarovnat vpravo do šířky 10 |
| `{x:<12}` | zarovnat vlevo do šířky 12 |
| `{x:>10.2f}` | obojí dohromady |

In [26]:
material = "C25/30"
objem = 25.0
cena_za_m3 = 2900

print(f"Beton {material}: {objem} m3")
print(f"Cena bez DPH: {objem * cena_za_m3} Kč")
print(f"Cena bez DPH: {objem * cena_za_m3:.2f} Kč")
print(f"Cena s DPH:   {objem * cena_za_m3 * 1.21:.2f} Kč")

Beton C25/30: 25.0 m3
Cena bez DPH: 72500.0 Kč
Cena bez DPH: 72500.00 Kč
Cena s DPH:   87725.00 Kč


Zarovnání se hodí na přehledné tabulky ve výpisu:

In [27]:
print(f"{'Polozka':<12}{'Mnozstvi':>10}{'Jednotka':>10}")
print(f"{'Beton':<12}{25.0:>10.2f}{'m3':>10}")
print(f"{'Vyztuz':<12}{1.85:>10.2f}{'t':>10}")
print(f"{'Bedneni':<12}{112.4:>10.2f}{'m2':>10}")

Polozka       Mnozstvi  Jednotka
Beton            25.00        m3
Vyztuz            1.85         t
Bedneni         112.40        m2


## 12. `input()` a `print()`

`input()` vypíše otázku a čeká na zadání. Vrací **vždy řetězec**, proto je pro
další počítání nutná konverze. Vyzkoušejte si v nové buňce:

```python
zadani = input("Zadejte tloustku desky v m: ")
tloustka = float(zadani)
print(f"Tloustka je {tloustka} m")
```

In [11]:
zadani = input("Zadejte tloustku desky v m: ")
tloustka = float(zadani)
print(f"Tloustka je {tloustka} m")

Tloustka je 10.0 m


In [8]:
print("a", "b", "c")               # hodnoty oddeli mezerou
print("a", "b", "c", sep="; ")     # vlastni oddelovac
print("bez odradkovani", end=" -> ")
print("pokracuje na stejnem radku")

a b c
a; b; c
bez odradkovani -> pokracuje na stejnem radku


## Shrnutí

| Typ | Co obsahuje | Příklad | Měnitelný |
|---|---|---|---|
| `int` | celé číslo | `25` | ne |
| `float` | desetinné číslo | `12.5` | ne |
| `bool` | `True` nebo `False` | `pruhyb < limit` | ne |
| `str` | text | `"C25/30"` | ne |
| `NoneType` | chybějící hodnota | `None` | ne |

Co si odnést:

* chybové hlášení se čte odspodu, poslední řádek řekne typ a příčinu
* `/` vrací `float`, `//` celé číslo, `%` zbytek
* desetinná čísla neporovnávejte pomocí `==`, použijte `math.isclose()`
* `input()` vrací řetězec, konverze je na vás
* řetězec je neměnný, metody vracejí nový řetězec
* f-string s `:.2f` je nejjednodušší cesta k čitelnému výpisu

V lekci 3 přidáme kolekce: seznamy, tuply, množiny a slovníky.